### ISSUE TITLE
Working demo?

### ISSUE THREAD

**Issue by MagePsycho** [kuafucode/magento-htmx#1]
I am big admirer or htmx / hotwire based development.
Do you have any working demo for Magento 2?

**Comment by ryansunxl** [comment]
Not at the moment but that is a good idea. I will setup a online demo.

**Comment by MagePsycho** [comment]
@kuafucode I Just installed the extension but didn't see any impact.
Is there any post-config thing to make it work with the default Luma theme?

**Comment by ryansunxl** [comment]
No post config, I just realized that htmx 2.0 is not working and I should load the AMD specific file. 
You can try htmx 1 in the initial commit. I'm fixing v2.

**Comment by MagePsycho** [comment]
Nice, it works perfectly. The screen viewport shifts slightly downward, but the difference in browsing speed is noticeable. It could be a game changer...

Auto scrolling by some margin while browsing the pages - is a bug currently?

**Comment by ryansunxl** [comment]
There are many subtle imperfect details that still need to be worked on, the auto-scrolling could be a bug or a feature 😉 feel free to to send PRs if you are interested on changing the behavior
